name: Sync Sigma Rules

on:
  schedule:
    - cron: '0 0 * * *'  # Daily
  workflow_dispatch:

jobs:
  sync-sigma-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true
        fetch-depth: 0  # Required for pushing

    - name: Clone Sigma upstream repo
      run: |
        git clone --depth 1 https://github.com/SigmaHQ/sigma.git sigma-upstream

    - name: Prepare folders
      run: |
        mkdir -p rules/linux rules/windows rules/network

    - name: Copy Sigma rules
      run: |
        cp -ruv sigma-upstream/rules/linux/* rules/linux/ || true
        cp -ruv sigma-upstream/rules/windows/* rules/windows/ || true
        cp -ruv sigma-upstream/rules/network/* rules/network/ || true

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Commit and push if there are changes
      run: |
        git add rules/
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Sigma rules on $(date -u)"
          git push origin main
        fi
